package br.com.conectatea.security;
import com.fasterxml.jackson.databind.ObjectMapper; import jakarta.servlet.*; import jakarta.servlet.http.*;
import java.io.IOException; import java.time.Instant; import java.util.Map; import java.util.concurrent.ConcurrentHashMap; import java.util.concurrent.atomic.AtomicInteger;
import org.springframework.http.MediaType; import org.springframework.web.filter.OncePerRequestFilter;
public class RateLimitFilter extends OncePerRequestFilter {
 private final Map<String,Window> windows=new ConcurrentHashMap<>(); private final ObjectMapper mapper; private final boolean enabled; private final int loginLimit; private final int tokenLimit; private final int passwordResetLimit; private final int emailVerificationLimit;
 public RateLimitFilter(ObjectMapper mapper,boolean enabled,int loginLimit,int tokenLimit,int passwordResetLimit,int emailVerificationLimit){this.mapper=mapper;this.enabled=enabled;this.loginLimit=loginLimit;this.tokenLimit=tokenLimit;this.passwordResetLimit=passwordResetLimit;this.emailVerificationLimit=emailVerificationLimit;}
 @Override protected void doFilterInternal(HttpServletRequest request,HttpServletResponse response,FilterChain chain)throws ServletException,IOException{int limit=limit(request);if(enabled&&limit>0&&exceeded(key(request),limit)){response.setStatus(429);response.setContentType(MediaType.APPLICATION_JSON_VALUE);response.setHeader("Retry-After","60");mapper.writeValue(response.getOutputStream(),Map.of("timestamp",Instant.now(),"status",429,"error","Too Many Requests","code","RATE_LIMITED","message","Muitas tentativas; aguarde e tente novamente","path",request.getRequestURI()));return;}chain.doFilter(request,response);}
 private int limit(HttpServletRequest request){String path=request.getRequestURI();if("POST".equals(request.getMethod())&&path.endsWith("/auth/login"))return loginLimit;if("POST".equals(request.getMethod())&&path.endsWith("/auth/password/forgot"))return passwordResetLimit;if("POST".equals(request.getMethod())&&path.endsWith("/auth/email-verification/request"))return emailVerificationLimit;if((path.contains("/tokens-vinculo")||path.contains("/vinculos/confirmar")||path.contains("/vinculos/tokens/"))&&!"OPTIONS".equals(request.getMethod()))return tokenLimit;return 0;}
 private String key(HttpServletRequest request){String value=request.getHeader("X-Forwarded-For");String ip=value==null?request.getRemoteAddr():value.split(",",2)[0].trim();String path=request.getRequestURI();String bucket=path.endsWith("/auth/login")?"login":path.endsWith("/auth/password/forgot")?"password-reset":path.endsWith("/auth/email-verification/request")?"email-verification":"token";return ip+':'+request.getMethod()+':'+bucket;}
 private boolean exceeded(String key,int limit){long now=System.currentTimeMillis();Window window=windows.compute(key,(ignored,current)->current==null||now-current.startedAt>=60000?new Window(now):current);return window.count.incrementAndGet()>limit;}
 private static final class Window{private final long startedAt;private final AtomicInteger count=new AtomicInteger();private Window(long startedAt){this.startedAt=startedAt;}}
}
