package br.com.conectatea.sessao.api; import br.com.conectatea.profissional.infrastructure.ProfissionalRepository; import br.com.conectatea.security.*; import br.com.conectatea.sessao.domain.*; import br.com.conectatea.sessao.infrastructure.SessaoRepository; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.OffsetDateTime; import java.util.List; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/sessoes") public class SessaoController { private final SessaoRepository sessions; private final ProfissionalRepository professionals; private final AuthorizationService authorization; public SessaoController(SessaoRepository s,ProfissionalRepository p,AuthorizationService a){sessions=s;professionals=p;authorization=a;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasRole('PROFISSIONAL')") public Response create(Authentication a,@Valid @RequestBody Request r){var u=(AuthenticatedUser)a.getPrincipal();authorization.requireCrianca(u,r.criancaId());var p=professionals.findByUsuarioId(u.id()).orElseThrow();return Response.from(sessions.save(new Sessao(r.dataHora(),r.duracao(),r.tipo(),r.descricao(),r.observacoes(),r.criancaId(),p.getId())));}
 @GetMapping public List<Response> list(Authentication a,@RequestParam(required=false)Long criancaId){var u=(AuthenticatedUser)a.getPrincipal();if(criancaId!=null){authorization.requireCrianca(u,criancaId);return sessions.findByCriancaId(criancaId).stream().map(Response::from).toList();}var p=professionals.findByUsuarioId(u.id()).orElseThrow();return sessions.findByProfissionalId(p.getId()).stream().map(Response::from).toList();}
 @PutMapping("/{id}") @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public Response update(Authentication a,@PathVariable Long id,@Valid @RequestBody Request r){var s=sessions.findById(id).orElseThrow();authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),s.getCriancaId());s.update(r.dataHora(),r.duracao(),r.tipo(),r.descricao(),r.observacoes());return Response.from(s);}
 @PatchMapping("/{id}/status") @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public Response status(Authentication a,@PathVariable Long id,@RequestBody StatusRequest r){var s=sessions.findById(id).orElseThrow();authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),s.getCriancaId());s.status(r.status());return Response.from(s);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasRole('PROFISSIONAL')") public void delete(Authentication a,@PathVariable Long id){var s=sessions.findById(id).orElseThrow();authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),s.getCriancaId());sessions.delete(s);}
 public record Request(@NotNull @FutureOrPresent OffsetDateTime dataHora,@Min(1) int duracao,@NotNull TipoSessao tipo,String descricao,String observacoes,@NotNull Long criancaId){} public record StatusRequest(@NotNull StatusSessao status){} public record Response(Long id,OffsetDateTime dataHora,int duracao,StatusSessao status,TipoSessao tipo,String descricao,String observacoes,Long criancaId){static Response from(Sessao s){return new Response(s.getId(),s.getDataHora(),s.getDuracao(),s.getStatus(),s.getTipo(),s.getDescricao(),s.getObservacoes(),s.getCriancaId());}}
}

