package br.com.conectatea.vinculo.application;
import br.com.conectatea.crianca.domain.Crianca; import br.com.conectatea.crianca.infrastructure.CriancaRepository; import br.com.conectatea.security.AuthenticatedUser; import br.com.conectatea.usuario.domain.TipoUsuario; import br.com.conectatea.vinculo.domain.*; import br.com.conectatea.vinculo.infrastructure.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.HexFormat; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class VinculoService { private final TokenVinculoRepository tokens; private final CriancaRepository children; private final VinculoResponsavelRepository links; private final ConsentimentoRepository consents; private final SecureRandom random=new SecureRandom(); public VinculoService(TokenVinculoRepository t,CriancaRepository c,VinculoResponsavelRepository l,ConsentimentoRepository x){tokens=t;children=c;links=l;consents=x;}
 @Transactional public GeneratedToken generate(Long criancaId,Long profissionalId){var raw=new byte[18];random.nextBytes(raw);var code=HexFormat.of().formatHex(raw).toUpperCase();tokens.save(new TokenVinculo(hash(code),criancaId,profissionalId,Instant.now().plus(7,ChronoUnit.DAYS)));return new GeneratedToken(code,Instant.now().plus(7,ChronoUnit.DAYS));}
 @Transactional(readOnly=true) public Preview preview(String code){var t=tokens.findByCodigoHash(hash(code)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Token inválido"));validate(t);var c=children.findById(t.getCriancaId()).orElseThrow();return new Preview(c.getId(),c.getNome(),c.getDataNascimento(),c.getGenero());}
 @Transactional public Preview confirm(String code,boolean accepted,AuthenticatedUser user,String ip,String agent){if(user.tipo()!=TipoUsuario.RESPONSAVEL)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Somente responsável pode confirmar vínculo");if(!accepted)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Consentimento obrigatório");var t=tokens.findByHashForUpdate(hash(code)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Token inválido"));validate(t);if(links.findByResponsavelIdAndCriancaId(user.id(),t.getCriancaId()).isEmpty())links.save(new VinculoResponsavelCrianca(user.id(),t.getCriancaId()));consents.save(new Consentimento(user.id(),t.getCriancaId(),t.getProfissionalId(),ip,agent));t.consumir();var c=children.findById(t.getCriancaId()).orElseThrow();return new Preview(c.getId(),c.getNome(),c.getDataNascimento(),c.getGenero());}
 @Transactional public void unlink(Long childId,AuthenticatedUser user){var link=links.findByResponsavelIdAndCriancaId(user.id(),childId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Vínculo não encontrado"));link.desvincular();}
 private void validate(TokenVinculo t){if(t.getStatus()!=StatusToken.PENDENTE)throw new ResponseStatusException(HttpStatus.GONE,"Token indisponível");if(!t.getExpiraEm().isAfter(Instant.now()))throw new ResponseStatusException(HttpStatus.GONE,"Token expirado");}
 private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.trim().toUpperCase().getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 public record GeneratedToken(String codigo,Instant expiraEm){} public record Preview(Long id,String nome,LocalDate dataNascimento,String genero){}
}
