package br.com.conectatea.meta.api;
import br.com.conectatea.meta.domain.*; import br.com.conectatea.meta.infrastructure.MetaRepository; import br.com.conectatea.profissional.infrastructure.ProfissionalRepository; import br.com.conectatea.progresso.domain.Progresso; import br.com.conectatea.progresso.infrastructure.ProgressoRepository; import br.com.conectatea.security.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.LocalDate; import java.util.List; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/metas") public class MetaController { private final MetaRepository metas; private final ProgressoRepository progress; private final ProfissionalRepository professionals; private final AuthorizationService authorization; public MetaController(MetaRepository m,ProgressoRepository p,ProfissionalRepository f,AuthorizationService a){metas=m;progress=p;professionals=f;authorization=a;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public Response create(Authentication a,@Valid @RequestBody Request r){var u=(AuthenticatedUser)a.getPrincipal();authorization.requireCrianca(u,r.criancaId());var p=professionals.findByUsuarioId(u.id()).orElseThrow();validateDates(r.dataInicio(),r.dataFim());return Response.from(metas.save(new Meta(r.titulo(),r.descricao(),r.categoria(),r.prioridade(),r.dataInicio(),r.dataFim(),r.criancaId(),p.getId())));}
 @GetMapping public List<Response> list(Authentication a,@RequestParam(required=false)Long criancaId){var u=(AuthenticatedUser)a.getPrincipal();if(criancaId!=null){authorization.requireCrianca(u,criancaId);return metas.findByCriancaId(criancaId).stream().map(Response::from).toList();}if(u.tipo()!=br.com.conectatea.usuario.domain.TipoUsuario.PROFISSIONAL)throw new org.springframework.security.access.AccessDeniedException("Filtro de criança obrigatório");var p=professionals.findByUsuarioId(u.id()).orElseThrow();return metas.findByProfissionalId(p.getId()).stream().map(Response::from).toList();}
 @GetMapping("/{id}") public Response get(Authentication a,@PathVariable Long id){var m=metas.findById(id).orElseThrow();authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),m.getCriancaId());return Response.from(m);}
 @PutMapping("/{id}") @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public Response update(Authentication a,@PathVariable Long id,@Valid @RequestBody Request r){var m=metas.findById(id).orElseThrow();authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),m.getCriancaId());validateDates(r.dataInicio(),r.dataFim());m.update(r.titulo(),r.descricao(),r.categoria(),r.prioridade(),r.dataInicio(),r.dataFim());return Response.from(m);}
 @PatchMapping("/{id}/progresso") @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public Response progress(Authentication a,@PathVariable Long id,@Valid @RequestBody ProgressRequest r){var m=metas.findById(id).orElseThrow();var u=(AuthenticatedUser)a.getPrincipal();authorization.requireCrianca(u,m.getCriancaId());var p=professionals.findByUsuarioId(u.id()).orElseThrow();int before=m.getProgresso();m.progress(r.progresso());progress.save(new Progresso(m.getId(),p.getId(),before,m.getProgresso(),m.getStatus(),r.descricao()));return Response.from(m);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public void delete(Authentication a,@PathVariable Long id){var m=metas.findById(id).orElseThrow();authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),m.getCriancaId());metas.delete(m);}
 private void validateDates(LocalDate i,LocalDate f){if(f.isBefore(i))throw new IllegalArgumentException("dataFim deve ser posterior à dataInicio");}
 public record Request(@NotBlank String titulo,String descricao,@NotNull CategoriaMeta categoria,@NotNull PrioridadeMeta prioridade,@NotNull @FutureOrPresent LocalDate dataInicio,@NotNull LocalDate dataFim,@NotNull Long criancaId){} public record ProgressRequest(@Min(0) @Max(100) int progresso,String descricao){} public record Response(Long id,String titulo,String descricao,CategoriaMeta categoria,PrioridadeMeta prioridade,StatusMeta status,int progresso,LocalDate dataInicio,LocalDate dataFim,Long criancaId){static Response from(Meta m){return new Response(m.getId(),m.getTitulo(),m.getDescricao(),m.getCategoria(),m.getPrioridade(),m.getStatus(),m.getProgresso(),m.getDataInicio(),m.getDataFim(),m.getCriancaId());}}
}
