package br.com.conectatea.vinculo.api;
import br.com.conectatea.crianca.api.CriancaController; import br.com.conectatea.crianca.infrastructure.CriancaRepository; import br.com.conectatea.security.AuthenticatedUser; import br.com.conectatea.vinculo.application.VinculoService; import br.com.conectatea.vinculo.application.CirculoService; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.List; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@io.swagger.v3.oas.annotations.tags.Tag(name="Vínculos")
@RestController @RequestMapping("/vinculos") public class VinculoController { private final VinculoService service; private final CirculoService circle; private final CriancaRepository children; public VinculoController(VinculoService s,CirculoService circle,CriancaRepository c){service=s;this.circle=circle;children=c;}
 @GetMapping("/tokens/{codigo}/preview") public VinculoService.Preview preview(@PathVariable String codigo){return service.preview(codigo);}
 @PostMapping("/confirmar") @PreAuthorize("hasRole('RESPONSAVEL')") public VinculoService.LinkRequest confirm(Authentication a,@Valid @RequestBody ConfirmRequest b,HttpServletRequest r){return service.confirm(b.codigo(),b.consentimentoAceito(),(AuthenticatedUser)a.getPrincipal(),r.getRemoteAddr(),r.getHeader("User-Agent"));}
 @PatchMapping("/criancas/{childId}/solicitacoes/{requestId}") @PreAuthorize("hasRole('RESPONSAVEL')") public VinculoService.LinkRequest decide(Authentication a,@PathVariable Long childId,@PathVariable Long requestId,@Valid @RequestBody DecisionRequest b){return service.decideRequest(childId,requestId,b.aprovar(),(AuthenticatedUser)a.getPrincipal());}
 @GetMapping("/me") @PreAuthorize("hasRole('RESPONSAVEL')") public List<CriancaController.ChildResponse> mine(Authentication a){return children.findLinkedToGuardian(((AuthenticatedUser)a.getPrincipal()).id()).stream().map(CriancaController.ChildResponse::from).toList();}
 @GetMapping("/solicitacoes/me") @PreAuthorize("hasRole('RESPONSAVEL')") public List<CirculoService.OwnRequestResponse> ownRequests(Authentication a){return circle.ownRequests((AuthenticatedUser)a.getPrincipal());}
 @DeleteMapping("/criancas/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasRole('RESPONSAVEL')") public void unlink(Authentication a,@PathVariable Long id){circle.leave((AuthenticatedUser)a.getPrincipal(),id);}
 public record ConfirmRequest(@NotBlank String codigo,@AssertTrue boolean consentimentoAceito){}
 public record DecisionRequest(boolean aprovar){}
}
