package br.com.conectatea.crianca.api;
import br.com.conectatea.crianca.domain.Crianca; import br.com.conectatea.crianca.infrastructure.CriancaRepository; import br.com.conectatea.profissional.infrastructure.ProfissionalRepository; import br.com.conectatea.security.*; import br.com.conectatea.usuario.domain.TipoUsuario; import br.com.conectatea.vinculo.domain.VinculoProfissionalCrianca; import br.com.conectatea.vinculo.infrastructure.VinculoProfissionalRepository; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.*; import java.util.List; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/criancas") public class CriancaController { private final CriancaRepository children; private final ProfissionalRepository professionals; private final VinculoProfissionalRepository links; private final AuthorizationService authorization; public CriancaController(CriancaRepository c,ProfissionalRepository p,VinculoProfissionalRepository l,AuthorizationService a){children=c;professionals=p;links=l;authorization=a;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public Response create(Authentication a,@Valid @RequestBody Request r){var uid=((AuthenticatedUser)a.getPrincipal()).id();var p=professionals.findByUsuarioId(uid).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Perfil profissional não encontrado"));var c=children.save(new Crianca(r.nome(),r.dataNascimento(),r.genero(),r.diagnostico(),r.diagnosticoDetalhes(),r.observacoes()));links.save(new VinculoProfissionalCrianca(p.getId(),c.getId()));return Response.from(c);}
 @GetMapping public List<Response> list(Authentication a){var u=(AuthenticatedUser)a.getPrincipal();var list=u.tipo()==TipoUsuario.PROFISSIONAL?professionals.findByUsuarioId(u.id()).map(p->children.findLinkedToProfessional(p.getId())).orElse(List.of()):children.findLinkedToGuardian(u.id());return list.stream().map(Response::from).toList();}
 @GetMapping("/{id}") public Response get(Authentication a,@PathVariable Long id){authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),id);return Response.from(children.findById(id).orElseThrow());}
 @PutMapping("/{id}") @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public Response update(Authentication a,@PathVariable Long id,@Valid @RequestBody Request r){authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),id);var c=children.findById(id).orElseThrow();c.update(r.nome(),r.dataNascimento(),r.genero(),r.diagnostico(),r.diagnosticoDetalhes(),r.observacoes());return Response.from(c);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasRole('PROFISSIONAL')") @Transactional public void archive(Authentication a,@PathVariable Long id){authorization.requireCrianca((AuthenticatedUser)a.getPrincipal(),id);children.findById(id).orElseThrow().arquivar();}
 public record Request(@NotBlank String nome,@NotNull @Past LocalDate dataNascimento,String genero,String diagnostico,String diagnosticoDetalhes,String observacoes){} public record Response(Long id,String nome,LocalDate dataNascimento,int idade,String genero,String diagnostico,String diagnosticoDetalhes,String observacoes){public static Response from(Crianca c){return new Response(c.getId(),c.getNome(),c.getDataNascimento(),Period.between(c.getDataNascimento(),LocalDate.now()).getYears(),c.getGenero(),c.getDiagnostico(),c.getDiagnosticoDetalhes(),c.getObservacoes());}}
}
