package br.com.conectatea.vinculo.application;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import br.com.conectatea.crianca.domain.Crianca;import br.com.conectatea.crianca.infrastructure.CriancaRepository;import br.com.conectatea.profissional.infrastructure.ProfissionalRepository;import br.com.conectatea.security.AuthenticatedUser;import br.com.conectatea.usuario.domain.*;import br.com.conectatea.usuario.infrastructure.UsuarioRepository;import br.com.conectatea.vinculo.domain.*;import br.com.conectatea.vinculo.infrastructure.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;import org.springframework.security.access.AccessDeniedException;import org.springframework.test.util.ReflectionTestUtils;
class ConviteNominalServiceTest{
 @Test void onlyCorrectConfirmedRecipientCanAcceptAndReplayIsRejected(){
  var invites=mock(ConviteCirculoRepository.class);var guardians=mock(VinculoResponsavelRepository.class);var professionalLinks=mock(VinculoProfissionalRepository.class);var professionals=mock(ProfissionalRepository.class);var users=mock(UsuarioRepository.class);var children=mock(CriancaRepository.class);var clock=Clock.fixed(Instant.parse("2026-10-10T12:00:00Z"),ZoneOffset.UTC);var service=new ConviteNominalService(invites,guardians,professionalLinks,professionals,users,children,clock);
  var managerLink=new VinculoResponsavelCrianca(1L,5L);managerLink.tornarGestor();when(guardians.lockActiveByChild(5L,StatusVinculo.VINCULADO)).thenReturn(List.of(managerLink));
  var child=new Crianca("Criança",LocalDate.of(2018,1,1),null,null,null,null);ReflectionTestUtils.setField(child,"id",5L);when(children.findById(5L)).thenReturn(Optional.of(child));
  var recipient=new Usuario("Família","family@example.com","hash",null,null,TipoUsuario.RESPONSAVEL);ReflectionTestUtils.setField(recipient,"id",2L);recipient.confirmarEmail(Instant.parse("2026-10-09T12:00:00Z"));when(users.findByEmailIgnoreCase("family@example.com")).thenReturn(Optional.of(recipient));when(users.findById(2L)).thenReturn(Optional.of(recipient));when(invites.save(any())).thenAnswer(i->i.getArgument(0));
  var issued=service.issue(new AuthenticatedUser(1L,"manager@example.com",TipoUsuario.RESPONSAVEL),5L,"family@example.com",PapelCirculo.RESPONSAVEL);var captured=org.mockito.ArgumentCaptor.forClass(ConviteCirculo.class);verify(invites).save(captured.capture());when(invites.findByHashForUpdate(anyString())).thenReturn(Optional.of(captured.getValue()));when(guardians.findByResponsavelIdAndCriancaId(2L,5L)).thenReturn(Optional.empty());
  assertThatThrownBy(()->service.accept(new AuthenticatedUser(3L,"other@example.com",TipoUsuario.RESPONSAVEL),issued.token())).isInstanceOf(AccessDeniedException.class);
  assertThat(service.accept(new AuthenticatedUser(2L,"family@example.com",TipoUsuario.RESPONSAVEL),issued.token()).status()).isEqualTo("ACEITO");verify(guardians).save(any(VinculoResponsavelCrianca.class));
  assertThatThrownBy(()->service.accept(new AuthenticatedUser(2L,"family@example.com",TipoUsuario.RESPONSAVEL),issued.token())).hasMessageContaining("Convite");
 }
}
