package br.com.conectatea.dashboard.api;
import br.com.conectatea.crianca.infrastructure.CriancaRepository; import br.com.conectatea.meta.infrastructure.MetaRepository; import br.com.conectatea.profissional.infrastructure.ProfissionalRepository; import br.com.conectatea.security.AuthenticatedUser; import br.com.conectatea.sessao.infrastructure.SessaoRepository; import java.time.*; import java.util.Map; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/dashboard") public class DashboardController { private final ProfissionalRepository professionals; private final CriancaRepository children; private final MetaRepository metas; private final SessaoRepository sessions; public DashboardController(ProfissionalRepository p,CriancaRepository c,MetaRepository m,SessaoRepository s){professionals=p;children=c;metas=m;sessions=s;}
 @GetMapping("/profissional") @PreAuthorize("hasRole('PROFISSIONAL')") public Map<String,Object> professional(Authentication a){var p=professionals.findByUsuarioId(((AuthenticatedUser)a.getPrincipal()).id()).orElseThrow();var cs=children.findLinkedToProfessional(p.getId());var ms=metas.findByProfissionalId(p.getId());var ss=sessions.findByProfissionalId(p.getId());var now=LocalDate.now();return Map.of("totalCriancas",cs.size(),"totalMetas",ms.size(),"metasEstaSemana",ms.stream().filter(m->!m.getDataFim().isAfter(now.plusDays(7))).count(),"metasEsteMes",ms.stream().filter(m->m.getDataFim().getMonth()==now.getMonth()&&m.getDataFim().getYear()==now.getYear()).count(),"totalSessoes",ss.size());}
 @GetMapping("/profissional/criancas") @PreAuthorize("hasRole('PROFISSIONAL')") public Object children(Authentication a){var p=professionals.findByUsuarioId(((AuthenticatedUser)a.getPrincipal()).id()).orElseThrow();return this.children.findLinkedToProfessional(p.getId());}
 @GetMapping("/profissional/metas") @PreAuthorize("hasRole('PROFISSIONAL')") public Object metas(Authentication a){var p=professionals.findByUsuarioId(((AuthenticatedUser)a.getPrincipal()).id()).orElseThrow();return metas.findByProfissionalId(p.getId());}
 @GetMapping("/responsavel") @PreAuthorize("hasRole('RESPONSAVEL')") public Map<String,Object> guardian(Authentication a){var cs=children.findLinkedToGuardian(((AuthenticatedUser)a.getPrincipal()).id());return Map.of("totalCriancas",cs.size(),"criancas",cs);}
}

