import type { MetasInfo } from '~/features/Metas/types'

export const metas: MetasInfo[] = [
  {
    id: 1,
    titulo: 'Melhorar comunicação verbal',
    categoria: 'COMUNICACAO',
    status: 'EM_ANDAMENTO',
    prioridade: 'MEDIA',
    progresso: 75,
    created_at: new Date(),
    updated_at: new Date(),
    descricao: 'Descrição da meta 1',
    profissional_id: 1,
    crianca_id: 1,
    crianca: {
      id: 1,
      nome: 'João Silva',
    },
    updates: [5, 10, 30, 30],
    data_inicio: new Date('2024-01-10'),
    data_fim: new Date('2024-04-10'),
  },
  {
    id: 2,
    titulo: 'Desenvolver habilidades sociais',
    categoria: 'SOCIAL',
    status: 'EM_ANDAMENTO',
    prioridade: 'ALTA',
    created_at: new Date(),
    updated_at: new Date(),
    descricao: 'Descrição da meta 2',
    profissional_id: 1,
    crianca_id: 2,
    data_inicio: new Date('2024-02-15'),
    data_fim: new Date('2024-05-15'),
    progresso: 45,
    crianca: {
      id: 2,
      nome: 'Maria Oliveira',
    },
    updates: [10, 15, 20],
  },
  {
    id: 3,
    titulo: 'Reduzir comportamentos repetitivos',
    categoria: 'COMPORTAMENTAL',
    status: 'QUASE_CONCLUIDA',
    prioridade: 'ALTA',
    created_at: new Date(),
    updated_at: new Date(),
    descricao: 'Descrição da meta 3',
    profissional_id: 1,
    crianca_id: 3,
    data_inicio: new Date('2023-11-30'),
    data_fim: new Date('2024-02-28'),
    progresso: 90,
    crianca: {
      id: 3,
      nome: 'Lucas Pereira',
    },
    updates: [10, 20, 25, 35],
  },
  {
    id: 4,
    titulo: 'Aumentar tempo de atenção focada',
    categoria: 'COGNITIVA',
    status: 'EM_ANDAMENTO',
    prioridade: 'BAIXA',
    created_at: new Date(),
    updated_at: new Date(),
    descricao: 'Descrição da meta 4',
    profissional_id: 1,
    crianca_id: 4,
    data_inicio: new Date('2024-01-09'),
    data_fim: new Date('2024-04-09'),
    progresso: 30,
    crianca: {
      id: 4,
      nome: 'Ana Costa',
    },
    updates: [5, 10, 15],
  },
]
